### ISSUE TITLE
Microverse Project: Set up your Kanban board 

### ISSUE THREAD

**Issue by Kashif-Saleem-Ghuman** [Kashif-Saleem-Ghuman/JavaScript-Capstone-Project#21]
Hello,
This is the issue opened for Review of the Microverse Project: Set up your Kanban board.

We copied the Template of Kanban Board from repo https://github.com/microverseinc/curriculum-javascript/projects/1 to this repo.
We installed jq tool locally on our machines.
We cloned the repo https://github.com/microverseinc/curriculum-tools-copy-projects.git and run the copy_github_board.sh bash script so it copies all of the cards from the Kanban Board to our project repo.
Link for our Github repository: https://github.com/Kashif-Saleem-Ghuman/JavaScript-Capstone-Project
We are a team of two people: @Kashif-Saleem-Ghuman  @ohyajk 

Cheers.

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this task! 👏 👏 
There are however a few issues that you still need to work on, but you are almost there! 🏎️ 🏎️

## Highlights 👍  
- Nice job for providing succinct description for the cards ❕ 

## Required Changes ♻️
- [x] Kindly note that, the total number of cards for a team of two should be equal to **15**.
- [x] Created cards appears not assigned! Kindy ensure that **all** cards are assigned to team members.
 _[Hint: doing so, you should see a circle with the user's avatar on each card. See the example below]:_
![image](https://user-images.githubusercontent.com/12745474/210245368-49322430-fe70-4e21-a704-1a50418c8ab8.png)

Cheers!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bimbolabuari** [comment]
Hello @Kashif-Saleem-Ghuman & @ohyajk  👋,

_This is an additional review due to the second opinion request._

- The total number of cards is 15 and all cards have been assigned equally.
  - I think the CR missed this because the card(s) 'C' was created for team member 3 and later removed.

As this was the only reason your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

**Comment by TuyishimireEric** [comment]
# Status: APPROVED 🟢  
### Hi  @Team 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️Professional Kanban board 👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ohyajk** [comment]
Thank you @bimbolabuari for your second opinion. We did everything as requested in the kanban project and after checking multiple times, asked review. It isn't very pleasant to see the required changes email after doing everything as given in the guideline. I sincerely request @rloterh to review the next projects appropriately so that students don't face any problems.

cheers,
Jitender Kumar (Jk)

**Comment by ohyajk** [comment]
Thank you @TuyishimireEric for your review. 

I also want to extend my regards to @Kashif-Saleem-Ghuman for helping in this project as coding partner.

cheers,
Jitender Kumar (JK)

**Comment by rloterh** [comment]
Hi @ohyajk & @Kashif-Saleem-Ghuman

I missed a vital step during the review process, and I sincerely apologize for the same. Please note this was not a deliberate attempt!

Thanks to @bimbolabuari and @TuyishimireEric for helping resolve the same 🙏 

Cheers! 😃

**Comment by Kashif-Saleem-Ghuman** [comment]
Hi @rloterh Apologies accepted 👍
